backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
collections:
  - label: "Artists"
    name: "artists"
    identifier_field: name
    folder: "src/artists"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Title", name: "role", widget: "string" }
      - { label: "Photo", name: "photo", widget: "image" }
      - { label: "Bio", name: "bio", widget: "text", required: false }
      - { label: "Instagram", name: "instagram", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Custom booking link", name: "booking", widget: "string", required: false }
      - label: "Gallery"
        name: "galleryImages"
        widget: "list"
        fields:
          - { label: "Image", name: "image", widget: "image" }
      - { label: "Order", name: "order", widget: "number" }
  - label: "Pages"
    name: "pages"
    editor:
      preview: false
    files:
      - label: "Homepage"
        name: homepage
        file: "src/_data/homepage.yaml"
        fields:
          - label: "Introduction"
            name: introduction
            widget: text
          - label: "Artists description"
            name: artists
            widget: text
      - label: "Client Expectations"
        name: expectations
        file: "src/_data/expectations.yaml"
        fields:
          - label: "Page Title"
            name: title
            widget: string
          - label: "Content"
            name: content
            widget: markdown
      - label: "About the Shop"
        name: about
        file: "src/_data/about_the_shop.yaml"
        fields:
          - label: "Page Title"
            name: title
            widget: string
          - label: "Content"
            name: content
            widget: markdown
          - label: "Gallery"
            name: "galleryImages"
            widget: "list"
            fields:
              - { label: "Image", name: "image", widget: "image" }
      - label: "Tattoo Care"
        name: care
        file: "src/_data/tattoo_care.yaml"
        fields:
          - label: "Page Title"
            name: title
            widget: string
          - label: "Content"
            name: content
            widget: markdown
      - label: "Merch Store"
        name: store
        file: "src/_data/store.yaml"
        fields:
          - label: "Page Title"
            name: title
            widget: string
          - label: "Content"
            name: content
            widget: markdown
            required: false
          - label: "Element"
            name: element
            widget: "code"
          - label: "Script"
            name: shopify_script
            widget: "code"
  - label: "Global Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Contact Info"
        name: "contact"
        file: "src/_data/contact.yaml"
        fields:
          - label: "Phone Number"
            name: phone
            widget: string
          - label: "Address Line 1"
            name: address_one
            widget: string
          - label: "Address Line 2"
            name: address_two
            widget: string
          - label: "Hours"
            name: "hours"
            widget: "list"
            fields:
              - { label: Day(s), name: days, widget: string }
              - { label: Hours, name: hours, widget: string }
